((emacs-lisp-mode . ((fill-column . 80)
                     (indent-tabs-mode . nil)
                     (sentence-end-double-space . t)
                     (eval . (put 'if-let* 'lisp-indent-function 2))
                     (eval . (put 'if-let 'lisp-indent-function 2))
                     (elisp-lint-indent-specs . ((if-let* . 2)
                                                 (if-let . 2)
                                                 (mcp-server-lib-test--with-server . defun)
                                                 (mcp-server-lib-test--with-servers . 1)
                                                 (mcp-server-lib-test--with-tools . 1)
                                                 (mcp-server-lib-test--with-resources . 1)
                                                 (mcp-server-lib-test--with-undefined-function . 1)
                                                 (mcp-server-lib-test--with-request . defun)
                                                 (mcp-server-lib-test--with-obsolete-tool-api . 0)
                                                 (mcp-server-lib-test--with-obsolete-resource-api . 0)
                                                 (mcp-server-lib-test--with-temp-install-dir . 0)
                                                 (mcp-server-lib-test--with-template-resources . 1)
                                                 (mcp-server-lib-test--do-describe-setup-test . 1)
                                                 (mcp-server-lib-test--check-resource-read-error . 0)
                                                 (mcp-server-lib-test--check-tool-call-error . 1)
                                                 (mcp-server-lib-ert-with-metrics-tracking . 1)
                                                 (mcp-server-lib-ert-verify-req-success . defun)
                                                 (mcp-server-lib-ert-with-server . defun)
                                                 (cl-defstruct . nil))))))